### ISSUE TITLE
Relicense to LGPLv2+?

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/pkcs11mod#73]
@aerth @bernard-wagner are you okay with relicensing pkcs11mod (and ncp11) from LGPLv3+ to LGPLv2+?   This would allow pkcs11mod to be used with applications licensed under GPLv2.  While I am personally very skeptical that loading a PKCS#11 module into an application is legally capable of creating a derivative work (I think PKCS#11 is an interface, so a copyright license like GPL cannot jump across it), there is not much (if any?) case law on this, and the legal uncertainty is not really desirable for us.  Also it's not great that pkcs11mod is more compatible with non-free software than with GPLv2 software.

**Comment by aerth** [comment]
yeah that works!

**Comment by JeremyRand** [comment]
Relicensed, thanks!
